### PR TITLE
Create root font size token

### PR DESCRIPTION
**Pull request by germain-gg**
All the font size calculations on web are based on the root element font size. It was hardcoded to `16px` in tokens.studio.

This pull request, create a token exposed to the projects, and configures tokens.studio to ingest that token for the font sizes calculations.

Would prevent hardcoded values as seen on https://github.com/matrix-org/matrix-hosted/pull/7950

### CODE REVIEW

**Review by janogarcia — COMMENTED** [review]
@germain-gg Just asking a few questions to double-check and get the whole context.

**On Tokens Studio and Figma**

As I understand, the newly added token definition `font.size.root`, exclusive to the Web platform, would only be used by Tokens Studio for the related `Base font size` setting, correct? We won't be generating a Figma style for it.

In that case, can we update the description to clarify it? Maybe adding the related Tokens Studio Docs URL? 

For example:

> `Configures the value 1rem represents. Used for Base Font Size setting in Tokens Studio. https://docs.tokens.studio/tokens/settings`

Or, maybe, if we want to mention that it's also used in the web codebase

> `Base font size for Tokens Studio and the root html element. https://docs.tokens.studio/tokens/settings`

**On Web codebase**

I guess you're planning to use `--cpd-font-size-root` to set the base font size for the `<html>` element so that we honor the user's system font size preference. Would that be the goal for that token?

I've always used `100%` for that purpose, but `1rem` should be equivalent in this case. I couldn't find any authoritative reference saying otherwise.

**Comment by janogarcia** [comment]
@germain-gg Also, related, although not strictly needed… We recently discussed how we could consume rems in the web codebase in a way that is still easy to reason about for developers and doesn't require using a CSS pre/post-processor. 

The technique below could be a nice, simple workaround. Those shouldn't be needed where we already provide semantic tokens. They may still be helpful, though, when transitioning legacy non-normalized values.

```
html {
  --14px: 0.875rem;
  --15px: 0.9375rem;
  --16px: 1rem;
  --17px: 1.0625rem;
  --18px: 1.125rem;
  --19px: 1.1875rem;
  --20px: 1.25rem;
  --21px: 1.3125rem;
}

h1 {
  font-size: var(--21px);
}
```

https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/#leveraging-css-variables-15

**Comment by germain-gg** [comment]
I've updated the description of the token and kept its value at `16px`.

Regarding the article, we already use a similar scale inside Element Web, see `_font-sizes.pcss`

**Comment by janogarcia** [comment]
@germain-gg That's good to know. Still, I mentioned it as we recently discussed how we could do such a thing without relying on CSS preprocessors. 👍

**Review by janogarcia — APPROVED** [review]

**Pull request merged**
