### PR TITLE
Add semantics tokens for alert component

### PR DESCRIPTION
**Pull request by gsouquet**
Needed for https://github.com/vector-im/compound-web/pull/6

Followed the values defined in https://www.figma.com/file/HUysJAhv6cK6p1Pc81Fxaa/Matrix-Authentication-Service-(MAS)?node-id=101%3A16968&t=xTdrcTANnzfzwsyn-1

Note that the action hue is set to `900` but it was set to `800` in the Figma document. I opted for `900` in the end as the already was `color.action.critical` that was set with a hue of `900` and I wanted to ensure consistency from that point of view

### CODE REVIEW

**Review by janogarcia — CHANGES_REQUESTED** [review]
In PR35 I renamed `color.bg.primary` to `color.bg.subtle-primary`, and `color.bg.secondary` to `color.bg.subtle-secondary`. 

After merging now we have both  `color.bg.primary` and `color.bg.subtle-primary`. We should remove `color.bg.primary` and `color.bg.secondary` in PR34.

---

In PR35 I reordered the top level groups for color tokens in `theme-semantics` token set to:

- text
- bg
- border
- icon

In PR34 they are back to:

- bg
- text
- border
- icon

---

In PR35 I created `icon.on-solid.primary` token, which now in PR34 has been moved to the border group `border.on-solid.primary`, which is wrong.

---

The icon `-alpha` tokens should come before the `icon.critical.` token group

---

Let's order the semantic states by decreasing severity:

- critical
- success
- info

Also, in some token groups those states are mixed with other stuff in between.

- In the `color.text` group, let's move `color.text.link` before critical/success/info.
- In the `color.icon` group, let's move `color.icon.accent` before critical/success/info.

**Comment by janogarcia** [comment]
@gsouquet Also, the breaking changes we should be aware of for any client consuming the previous tokens:

- `color.bg.action.primary` → `color.bg.action.primary.rest`
- `color.bg.canvas` → `color.bg.canvas.default`
- `color.text.action.primary` → `color.text.critical.primary`
- `color.bg.primary` → `color.bg.subtle-primary`
- `color.bg.secondary` → `color.bg.subtle-secondary`

Unsure how we are going to handle such migrations/deprecations on the target platforms.

As for the design side, in Tokens Studio, the keys for the style names have been updated while the associated Figma IDs have been preserved:
https://github.com/vector-im/compound-design-tokens/blob/gsouquet/alert/tokens/%24themes.json#L331-L335

Once we merge this PR, I'll need to test that Tokens Studio also auto-renames the Figma Styles in the production Compound Styles library as expected, or otherwise rename them manually if necessary (hopefully not necessary based on previous tests, but I'm not 101% sure).

**Comment by gsouquet** [comment]
Thank you for the review.

> Unsure how we are going to handle such migrations/deprecations on the target platforms.

It does not matter, no one uses that in production today!

**Comment by janogarcia** [comment]
Forgot to add in the review a comment on all those missing token descriptions.

---

**Background**

- `color.bg.success.subtle`: Subtle background colour for success state elements. State: Rest.
- `color.bg.info.subtle`: Subtle background colour for informational elements. State: Rest.

**Border**

- `color.border.critical.subtle`: Subtle border colour for critical state elements.
- `color.border.success.subtle`: Subtle border colour for success state elements.
- `color.border.info.subtle`: Subtle border colour for informational elements.

**Text**

- `color.text.success.primary`: Accent text colour for success state elements.
- `color.text.info.primary`: Accent text colour for informational elements.

**Icons**

- `color.icon.success.primary`: High-contrast icon for success state elements.
- `color.icon.info.primary`: High-contrast icon for informational elements.
- `color.icon.primary-alpha`: Translucent version of primary icon. Refer to it for intended use.
- `color.icon.secondary-alpha`: Translucent version of secondary icon. Refer to it for intended use.
- `color.icon.tertiary-alpha`: Translucent version of tertiary icon. Refer to it for intended use.
- `color.icon.quaternary-alpha`: Translucent version of quaternary icon. Refer to it for intended use.

**Review by janogarcia — CHANGES_REQUESTED** [review]
**.on-solid** 

Refer to the token descriptions to move them to the correct group. Currently, the icon one is in the border group, and the text one in the icon group.

**color.icon.disabled**

Make all solid colors happen before the translucent ones, including `color.icon.disabled`.

**Review by janogarcia — APPROVED** [review]

**Pull request closed without merging**
